# Generated by Django 3.2.8 on 2022-04-16 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='UserAccount',
            new_name='userAccount',
        ),
    ]
