# Generated by Django 3.2.13 on 2022-04-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_useraccount_address_useraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='profile_image',
            field=models.ImageField(default='account/profile_image', null=True, upload_to='account/profile_image'),
        ),
    ]
